"""
Django settings for mi_cine project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import socket
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# =============================================================================
# CARGA DE VARIABLES DE ENTORNO (.env)
# =============================================================================
# python-dotenv busca un archivo .env en el directorio backend/.
# En local, las variables se leen de backend/.env
# En producción, las variables se inyectan como variables de entorno del sistema.
load_dotenv(BASE_DIR / '.env')


# =============================================================================
# ENTORNO: LOCAL vs PRODUCCIÓN
# =============================================================================
# True  = desarrollo local
# False = producción / staging
# Prioridad: variable de entorno > hostname 'PC-ASH' > False
DEBUG = os.getenv('DJANGO_DEBUG', str(socket.gethostname() == 'PC-ASH')).lower() in ('true', '1', 'yes')


# =============================================================================
# SEGURIDAD
# =============================================================================
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    # Fallback SOLO para desarrollo local; en producción DEBE definirse en el .env
    'django-insecure-dev-only-change-in-production-xyz789'
)

# Dominio de producción (usado en ALLOWED_HOSTS, CORS, CSRF)
# Mantiene compatibilidad con el nombre antiguo CLOUDFLARE_URL
PRODUCTION_DOMAIN = os.getenv('PRODUCTION_DOMAIN', os.getenv('CLOUDFLARE_URL', ''))


# =============================================================================
# ALLOWED HOSTS
# =============================================================================
# En producción: definir DJANGO_ALLOWED_HOSTS con dominios separados por coma
# En local: se construye automáticamente con localhost + IPs comunes
_DEFAULT_HOSTS = 'localhost,127.0.0.1,172.20.47.95,192.168.2.204,217.154.178.102,cine.grancanash.es'
_ALLOWED_HOSTS_ENV = os.getenv('DJANGO_ALLOWED_HOSTS', _DEFAULT_HOSTS)
ALLOWED_HOSTS = [h.strip() for h in _ALLOWED_HOSTS_ENV.split(',') if h.strip()]

# Añadir dominio de producción si está definido y no duplicado
if PRODUCTION_DOMAIN and PRODUCTION_DOMAIN not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(PRODUCTION_DOMAIN)


# =============================================================================
# APLICACIONES
# =============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',

    # other Django apps
    'rest_framework',

    # nuestras apps
    "accounts",
    "core",
    "titles",
    "catalogs",
    "tracking",

]

AUTH_USER_MODEL = "accounts.CustomUser"

if DEBUG:
    # Add django_browser_reload only in DEBUG mode
    INSTALLED_APPS += ["django_browser_reload"]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if DEBUG:
    # Add django_browser_reload middleware only in DEBUG mode
    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]

ROOT_URLCONF = 'mi_cine.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mi_cine.wsgi.application'


# =============================================================================
# BASE DE DATOS
# =============================================================================
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.getenv('DB_NAME', 'mi_cine'),
        'USER': os.getenv('DB_USER', 'usuario'),
        'PASSWORD': os.getenv('DB_PASSWORD', '123456'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
    },
}


# =============================================================================
# VALIDACIÓN DE CONTRASEÑAS
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =============================================================================
# INTERNACIONALIZACIÓN
# =============================================================================

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# =============================================================================
# ARCHIVOS ESTÁTICOS
# =============================================================================

STATIC_URL = 'static/'

# Carpeta donde Django recopila los archivos estáticos en producción
# (solo se usa cuando ejecutas collectstatic)
STATIC_ROOT = BASE_DIR / 'staticfiles'


# =============================================================================
# CONFIGURACIÓN POR DEFECTO
# =============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================================================
# EMAIL
# =============================================================================

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@micien.com'


# =============================================================================
# INTERNAL IPS (django-debug-toolbar)
# =============================================================================

INTERNAL_IPS = [
    "127.0.0.1",
]


# =============================================================================
# TMDB (The Movie Database) — API externa
# =============================================================================

TMDB_ACCESS_TOKEN = os.getenv(
    'TMDB_ACCESS_TOKEN',
    'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzNWM4YzgxM2VkMmIyZjY1ZWRmNDAwMmI2ODRiYjI2OCIsIm5iZiI6MTc2OTQ0NDgxNC40NjQsInN1YiI6IjY5Nzc5NWNlNmM4OWRiMWVlZWI2ODY2NyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.n8uJwuJBxK-nZFVXHk4-xUfTWJJJkJL-LzsGngqmCEk'
)


# =============================================================================
# DJANGO REST FRAMEWORK
# =============================================================================

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 24,
}


# =============================================================================
# CORS + CSRF
# =============================================================================
# Orígenes por defecto para desarrollo local
_DEFAULT_CORS = 'http://localhost:5173,http://127.0.0.1:5173,http://192.168.2.204:5173'
_CORS_ENV = os.getenv('CORS_ALLOWED_ORIGINS', _DEFAULT_CORS)
CORS_ALLOWED_ORIGINS = [o.strip() for o in _CORS_ENV.split(',') if o.strip()]

if PRODUCTION_DOMAIN:
    CORS_ALLOWED_ORIGINS.append(f"https://{PRODUCTION_DOMAIN}")

CORS_ALLOW_CREDENTIALS = True

# CSRF
_CSRF_ENV = os.getenv('CSRF_TRUSTED_ORIGINS', _DEFAULT_CORS)
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _CSRF_ENV.split(',') if o.strip()]

if PRODUCTION_DOMAIN:
    CSRF_TRUSTED_ORIGINS.append(f"https://{PRODUCTION_DOMAIN}")


# =============================================================================
# SEGURIDAD ADICIONAL EN PRODUCCIÓN
# =============================================================================
if not DEBUG:
    # Redirigir HTTP → HTTPS (el proxy de Cloudflare ya lo hace, pero por si acaso)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
