# Generated by Django 6.0.2 on 2026-02-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('original_title', models.CharField(blank=True, max_length=200, verbose_name='Título original')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('type', models.CharField(choices=[('movie', 'Película'), ('series', 'Serie')], max_length=10, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('seasons', models.PositiveIntegerField(default=1, verbose_name='Temporadas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('actors', models.ManyToManyField(blank=True, related_name='titles', to='catalogs.actor', verbose_name='Actores')),
                ('categories', models.ManyToManyField(blank=True, related_name='titles', to='catalogs.category', verbose_name='Géneros')),
                ('platforms', models.ManyToManyField(blank=True, related_name='titles', to='catalogs.platform', verbose_name='Plataforma')),
            ],
        ),
    ]
