# Generated by Django 6.0.2 on 2026-02-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_title_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año'),
        ),
    ]
