name: Deploy frontend to VPS

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy frontend on VPS
        # run: |
        #   ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
        #     cd /var/www/mi_cine && \
        #     git pull origin main && \
        #     cd frontend && \
        #     npm install && \
        #     npm run build && \
        #     mkdir -p /var/www/mi_cine/frontend_dist && \
        #     rm -rf /var/www/mi_cine/frontend_dist/* && \
        #     cp -r dist/* /var/www/mi_cine/frontend_dist/
        #   "
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd /var/www/mi_cine && \
            git fetch origin main && git reset --hard origin/main
            cd frontend && \
            npm ci && \
            npm run build && \
            mkdir -p /var/www/mi_cine/frontend_dist && \
            rm -rf /var/www/mi_cine/frontend_dist/* && \
            cp -r dist/* /var/www/mi_cine/frontend_dist/
          "
